### ISSUE TITLE
optionalPeerDependencies do not exist

### ISSUE THREAD

**Issue by conradstrassburger** [T-Systems-MMS/aurelia-components#47]
I stumbled across this again while developing a PR.
In [package.json](https://github.com/T-Systems-MMS/aurelia-components/blob/master/package.json#L13) "`optionalPeerDependencies`" are defined. According to the npm docs, there is no such thing. When running npm install in any configuration, these dependencies aren't installed.

[`peerDependencies`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies) and [`optionalDependencies`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#optionaldependencies) exist on their own.

I'd argue that for here, `peerDependencies` would be just fine.
If truly optional peer dependencies are what is wanted, one needs to use [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta).

**Comment by Zsar** [comment]
Yes, this is an odd thing. It is present in IntelliJ IDEA's autocomplete support for `package.json` and "seems to do the right thing"... but arguably, doing nothing is mostly the right thing in this case, so that's kind of a low bar here.

... I am beginning to thing that this is some sort of solo effort on the part of Jetbrains though, so all in favour of replacing it with the documented version. All listed `optionalPeerDependencies` should thence be converted to have an `"optional": true` entry in `peerDependenciesMeta` as per regular npm documentation.
